config: conf/toy.yaml
inherit:
- /home/mwilcoxson/Code/CS182Project/src/conf/models/standard.yaml
- /home/mwilcoxson/Code/CS182Project/src/conf/wandb.yaml
model:
  family: gpt2
  n_dims: 5
  n_embd: 256
  n_head: 8
  n_layer: 12
  n_positions: 21
out_dir: ../models/kernel_linear_regression/d4ef06c8-d272-4774-826c-4a13bbb12d8a
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 5
      inc: 1
      interval: 2000
      start: 5
    points:
      end: 21
      inc: 1
      interval: 1000
      start: 11
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 0.0001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: kernel_linear_regression
  task_kwargs:
    basis_dim: 2
  train_steps: 150001
wandb:
  entity: cs182-project
  log_every_steps: 100
  name: kernel_linear_regression_toy
  notes: ''
  project: in-context-training
